/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FacetSortCriterion } from "@coveo/headless";
export namespace Components {
    interface AtomicIconFacet {
        /**
          * Specifies an explicit list of `allowedValues` in the Search API request, as a JSON string representation.  If you specify a list of values for this option, the facet uses only these values (if they are available in the current result set).  Example:  The following facet only uses the `Contact`, `Account`, and `File` values of the `objecttype` field. Even if the current result set contains other `objecttype` values, such as `Message`, or `Product`, the facet does not use those other values.  ```html <atomic-facet field="objecttype" allowed-values='["Contact","Account","File"]'></atomic-facet> ```  The maximum amount of allowed values is 25.  Default value is `undefined`, and the facet uses all available values for its `field` in the current result set.
         */
        "allowedValues": string[] | string;
        /**
          * The required facets and values for this facet to be displayed. Examples: ```html <atomic-facet facet-id="abc" field="objecttype" ...></atomic-facet>  <!-- To show the facet when any value is selected in the facet with id "abc": --> <atomic-facet   depends-on-abc   ... ></atomic-facet>  <!-- To show the facet when value "doc" is selected in the facet with id "abc": --> <atomic-facet   depends-on-abc="doc"   ... ></atomic-facet> ```
         */
        "dependsOn": Record<string, string>;
        /**
          * Whether to display the facet values as checkboxes (multiple selection), links (single selection) or boxes (multiple selection). Possible values are 'checkbox', 'link', and 'box'.
         */
        "displayValuesAs": 'checkbox' | 'link' | 'box';
        /**
          * Whether to allow excluding values from the facet.
         */
        "enableExclusion": boolean;
        /**
          * Specifies a unique identifier for the facet.
         */
        "facetId"?: string;
        /**
          * The field whose values you want to display in the facet.
         */
        "field": string;
        /**
          * Whether to exclude the parents of folded results when estimating the result count for each facet value.   Note: Resulting count is only an estimation, in some cases this value could be incorrect.
         */
        "filterFacetCount": boolean;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the heading over the facet, from 1 to 6.
         */
        "headingLevel": number;
        /**
          * The maximum number of results to scan in the index to ensure that the facet lists all potential facet values. Note: A high injectionDepth may negatively impact the facet request performance. Minimum: `0` Default: `1000`
         */
        "injectionDepth": number;
        /**
          * Specifies whether the facet is collapsed. When the facet is the child of an `atomic-facet-manager` component, the facet manager controls this property.
         */
        "isCollapsed": boolean;
        /**
          * The non-localized label for the facet. Used in the `atomic-breadbox` component through the bindings store.
         */
        "label": string;
        /**
          * The number of values to request for this facet. Also determines the number of additional values to request each time more values are shown.
         */
        "numberOfValues": number;
        /**
          * The sort criterion to apply to the returned facet values. Possible values are 'score', 'alphanumeric',  'occurrences',  'score' and 'automatic'.
         */
        "sortCriteria": FacetSortCriterion;
    }
}
declare global {
    interface HTMLAtomicIconFacetElement extends Components.AtomicIconFacet, HTMLStencilElement {
    }
    var HTMLAtomicIconFacetElement: {
        prototype: HTMLAtomicIconFacetElement;
        new (): HTMLAtomicIconFacetElement;
    };
    interface HTMLElementTagNameMap {
        "atomic-icon-facet": HTMLAtomicIconFacetElement;
    }
}
declare namespace LocalJSX {
    interface AtomicIconFacet {
        /**
          * Specifies an explicit list of `allowedValues` in the Search API request, as a JSON string representation.  If you specify a list of values for this option, the facet uses only these values (if they are available in the current result set).  Example:  The following facet only uses the `Contact`, `Account`, and `File` values of the `objecttype` field. Even if the current result set contains other `objecttype` values, such as `Message`, or `Product`, the facet does not use those other values.  ```html <atomic-facet field="objecttype" allowed-values='["Contact","Account","File"]'></atomic-facet> ```  The maximum amount of allowed values is 25.  Default value is `undefined`, and the facet uses all available values for its `field` in the current result set.
         */
        "allowedValues"?: string[] | string;
        /**
          * The required facets and values for this facet to be displayed. Examples: ```html <atomic-facet facet-id="abc" field="objecttype" ...></atomic-facet>  <!-- To show the facet when any value is selected in the facet with id "abc": --> <atomic-facet   depends-on-abc   ... ></atomic-facet>  <!-- To show the facet when value "doc" is selected in the facet with id "abc": --> <atomic-facet   depends-on-abc="doc"   ... ></atomic-facet> ```
         */
        "dependsOn"?: Record<string, string>;
        /**
          * Whether to display the facet values as checkboxes (multiple selection), links (single selection) or boxes (multiple selection). Possible values are 'checkbox', 'link', and 'box'.
         */
        "displayValuesAs"?: 'checkbox' | 'link' | 'box';
        /**
          * Whether to allow excluding values from the facet.
         */
        "enableExclusion"?: boolean;
        /**
          * Specifies a unique identifier for the facet.
         */
        "facetId"?: string;
        /**
          * The field whose values you want to display in the facet.
         */
        "field": string;
        /**
          * Whether to exclude the parents of folded results when estimating the result count for each facet value.   Note: Resulting count is only an estimation, in some cases this value could be incorrect.
         */
        "filterFacetCount"?: boolean;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the heading over the facet, from 1 to 6.
         */
        "headingLevel"?: number;
        /**
          * The maximum number of results to scan in the index to ensure that the facet lists all potential facet values. Note: A high injectionDepth may negatively impact the facet request performance. Minimum: `0` Default: `1000`
         */
        "injectionDepth"?: number;
        /**
          * Specifies whether the facet is collapsed. When the facet is the child of an `atomic-facet-manager` component, the facet manager controls this property.
         */
        "isCollapsed"?: boolean;
        /**
          * The non-localized label for the facet. Used in the `atomic-breadbox` component through the bindings store.
         */
        "label"?: string;
        /**
          * The number of values to request for this facet. Also determines the number of additional values to request each time more values are shown.
         */
        "numberOfValues"?: number;
        /**
          * The sort criterion to apply to the returned facet values. Possible values are 'score', 'alphanumeric',  'occurrences',  'score' and 'automatic'.
         */
        "sortCriteria"?: FacetSortCriterion;
    }
    interface IntrinsicElements {
        "atomic-icon-facet": AtomicIconFacet;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "atomic-icon-facet": LocalJSX.AtomicIconFacet & JSXBase.HTMLAttributes<HTMLAtomicIconFacetElement>;
        }
    }
}
