/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Sample custom Atomic result component, to be used inside an Atomic Result Template.
     * This component showcases a component that conditionally renders the author of a result, with a fallback to display "anonymous" in the event that no author is available for a document, for educational purposes.
     * In a real life scenario, we recommend using [result-field-condition](https://docs.coveo.com/en/atomic/latest/reference/result-template-components/atomic-field-condition/) and [atomic-result-text](https://docs.coveo.com/en/atomic/latest/reference/result-template-components/atomic-result-text/).
     */
    interface FacilityIcon {
        "field": string;
    }
}
declare global {
    /**
     * Sample custom Atomic result component, to be used inside an Atomic Result Template.
     * This component showcases a component that conditionally renders the author of a result, with a fallback to display "anonymous" in the event that no author is available for a document, for educational purposes.
     * In a real life scenario, we recommend using [result-field-condition](https://docs.coveo.com/en/atomic/latest/reference/result-template-components/atomic-field-condition/) and [atomic-result-text](https://docs.coveo.com/en/atomic/latest/reference/result-template-components/atomic-result-text/).
     */
    interface HTMLFacilityIconElement extends Components.FacilityIcon, HTMLStencilElement {
    }
    var HTMLFacilityIconElement: {
        prototype: HTMLFacilityIconElement;
        new (): HTMLFacilityIconElement;
    };
    interface HTMLElementTagNameMap {
        "facility-icon": HTMLFacilityIconElement;
    }
}
declare namespace LocalJSX {
    /**
     * Sample custom Atomic result component, to be used inside an Atomic Result Template.
     * This component showcases a component that conditionally renders the author of a result, with a fallback to display "anonymous" in the event that no author is available for a document, for educational purposes.
     * In a real life scenario, we recommend using [result-field-condition](https://docs.coveo.com/en/atomic/latest/reference/result-template-components/atomic-field-condition/) and [atomic-result-text](https://docs.coveo.com/en/atomic/latest/reference/result-template-components/atomic-result-text/).
     */
    interface FacilityIcon {
        "field"?: string;
    }
    interface IntrinsicElements {
        "facility-icon": FacilityIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Sample custom Atomic result component, to be used inside an Atomic Result Template.
             * This component showcases a component that conditionally renders the author of a result, with a fallback to display "anonymous" in the event that no author is available for a document, for educational purposes.
             * In a real life scenario, we recommend using [result-field-condition](https://docs.coveo.com/en/atomic/latest/reference/result-template-components/atomic-field-condition/) and [atomic-result-text](https://docs.coveo.com/en/atomic/latest/reference/result-template-components/atomic-result-text/).
             */
            "facility-icon": LocalJSX.FacilityIcon & JSXBase.HTMLAttributes<HTMLFacilityIconElement>;
        }
    }
}
